Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-12, with the labels that each got.

#240 Revert `SPPF` to `SPP`
  yolort/models/darknetv4.py
  yolort/models/path_aggregation_network.py
Labels: bug / fix

#241 Fix package version in setuptools
  .pre-commit-config.yaml
  setup.py
Labels: documentation, dependencies

#242 Remove low scoring filter from LogitsDecoder
  test/test_relaying.py
  test/test_runtime.py
  yolort/models/box_head.py
  yolort/relaying/__init__.py
  yolort/relaying/yolo_inference.py
  yolort/runtime/__init__.py
  yolort/runtime/yolo_tensorrt_model.py
Labels: enhancement, deployment

#245 [WIP] Add TensorRT C++ interface for yolort
  deployment/tensorrt/CMakeLists.txt
  deployment/tensorrt/cmdline.h
  deployment/tensorrt/main.cpp
Labels: enhancement, deployment

#243 Add tensorrt export tools
  .github/workflows/ci-test.yml
  .gitignore
  test/test_runtime.py
  yolort/models/box_head.py
  yolort/runtime/__init__.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/yolo_graphsurgeon.py
  yolort/runtime/yolo_tensorrt_model.py
Labels: enhancement, deployment

#246 Cleanup unit-test
  .github/workflows/ci-test.yml
Labels: code quality

#203 Cleanup AnchorGenerator and PostProcess
  test/test_models.py
  test/test_models_anchor_utils.py
  yolort/models/_utils.py
  yolort/models/anchor_utils.py
  yolort/models/box_head.py
  yolort/models/yolo.py
  yolort/runtime/yolo_tensorrt_model.py
  yolort/v5/models/common.py
  yolort/v5/utils/general.py
Labels: enhancement, code quality, bc-breaking

#250 Set argument `image_size` configurable in export_model.py
  tools/export_model.py
Labels: enhancement

#251 Add TensorRT Python interface and CLI
  tools/detect.py
  yolort/models/box_head.py
  yolort/runtime/__init__.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_tensorrt.py
  yolort/runtime/yolo_tensorrt_model.py
  yolort/utils/image_utils.py
  yolort/v5/utils/datasets.py
  yolort/v5/utils/general.py
Labels: enhancement, API

#252 Fix register_nms in `YOLOGraphSurgeon`
  test/test_runtime.py
  tools/detect.py
  yolort/models/box_head.py
  yolort/runtime/__init__.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_tensorrt.py
  yolort/runtime/yolo_graphsurgeon.py
  yolort/runtime/yolo_tensorrt_model.py
Labels: bug / fix

#253 Add TensorRT export and inference notebooks
  docs/source/index.rst
  docs/source/notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
Labels: enhancement

#254 Refactor module structure for exporting TensorRT
  test/test_runtime.py
  yolort/models/box_head.py
  yolort/runtime/trt_helper.py
  yolort/runtime/yolo_graphsurgeon.py
  yolort/runtime/yolo_tensorrt_model.py
Labels: API, code quality

#255 Upgrade PyTorch to 1.10.1 in GH Actions
  .github/workflows/ci-test.yml
Labels: code quality

#256 Move `LogitsDecoder` into trt_helper.py and fix docstrings
  yolort/models/box_head.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_tensorrt.py
Labels: documentation, API

#259 Remove unused parameters in PredictorTRT
  yolort/runtime/y_tensorrt.py
Labels: code quality

#261 Support yolov5x and yolov5x6 models
  yolort/models/__init__.py
  yolort/models/darknet.py
  yolort/models/darknetv6.py
  yolort/models/yolo.py
  yolort/v5/helper.py
Labels: enhancement

#263 Remove expired parameters in detect.py
  tools/detect.py
Labels: bug / fix
