Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-04, with the labels that each got.

#87 Support training with vanilla module
  test/test_data_pipeline.py
  test/test_engine.py
  test/test_models_utils.py
  test/test_torchscript.py
  yolort/models/box_head.py
  yolort/models/yolo.py
  yolort/models/yolo_module.py
  yolort/utils/__init__.py
  yolort/utils/file_utils.py
Labels: bugfix, enhancement

#88 Refactor data pipeline
  test/test_data_pipeline.py
  test/test_engine.py
  test/test_image_utils.py
  test/test_models.py
  test/test_onnx.py
  test/test_utils.py
  yolort/__init__.py
  yolort/data/__init__.py
  yolort/data/coco.py
  yolort/data/coco_eval.py
  yolort/data/data_module.py
  yolort/data/data_pipeline.py
  yolort/data/detection_pipeline.py
  yolort/data/transforms.py
  yolort/data/voc.py
  yolort/data/voc_eval.py
  yolort/datasets/__init__.py
  yolort/models/yolo_module.py
  yolort/train.py
Labels: enhancement

#89 Add mAP Metrics and validation
  .gitignore
  requirements.txt
  test/dataset_utils.py
  test/test_data_pipeline.py
  test/test_engine.py
  yolort/data/__init__.py
  yolort/data/_helper.py
  yolort/data/coco.py
  yolort/data/coco_eval.py
  yolort/data/data_module.py
  yolort/data/distributed.py
  yolort/data/voc_eval.py
  yolort/models/yolo_module.py
  yolort/utils/__init__.py
  yolort/utils/file_utils.py
  yolort/utils/logger.py
Labels: enhancement

#93 Add validation methods in tasks
  test/test_data_pipeline.py
  test/test_engine.py
  yolort/data/_helper.py
  yolort/models/_utils.py
  yolort/models/yolo_module.py
Labels: enhancement

#97 Bug fixes in read_image_to_tensor
  notebooks/inference-pytorch-export-libtorch.ipynb
  yolort/utils/image_utils.py
Labels: bugfix
