Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-09, with the labels that each got.

#143 Fixing `build_targets` in `SetCriterion`
  test/test_engine.py
  test/test_models.py
  test/test_models_utils.py
  yolort/models/_utils.py
  yolort/models/box_head.py
  yolort/models/yolo.py
Labels: enhancement

#161 Upgrade PT to 1.9.0 in unit-test
  .github/workflows/ci_test.yml
  test/common_utils.py
  test/test_data_pipeline.py
  test/test_engine.py
  test/test_image_utils.py
  test/test_models.py
  test/test_models_anchor_utils.py
  test/test_models_common.py
  test/test_models_transform.py
  test/test_onnx.py
  test/test_torchscript.py
  test/test_utils.py
Labels: code quality

#162 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement, code quality

#165 Refactor graph visualization
  notebooks/export-relay-inference-tvm.ipynb
  notebooks/model-graph-visualization.ipynb
  test/test_relaying.py
  yolort/relaying/__init__.py
  yolort/relaying/ir_visualizer.py
  yolort/relaying/trace_wrapper.py
  yolort/utils/graph_utils.py
Labels: enhancement, code quality

#168 Add ultralytics/yolov5 to yolort
  .gitignore
  configs/coco128.yaml
  configs/hyp.scratch.yaml
  configs/yolov5s.yaml
  tools/train_vanilla.py
  yolort/models/common.py
  yolort/utils/augmentations.py
  yolort/utils/autoanchor.py
  yolort/utils/callbacks.py
  yolort/utils/common.py
  yolort/utils/datasets.py
  yolort/utils/downloads.py
  yolort/utils/general.py
  yolort/utils/loggers/__init__.py
  yolort/utils/loggers/wandb/README.md
  yolort/utils/loggers/wandb/__init__.py
  yolort/utils/loggers/wandb/log_dataset.py
  yolort/utils/loggers/wandb/sweep.py
  yolort/utils/loggers/wandb/sweep.yaml
  yolort/utils/loggers/wandb/wandb_utils.py
  yolort/utils/loss.py
  yolort/utils/metrics.py
  yolort/utils/plots.py
  yolort/utils/torch_utils.py
  yolort/utils/val.py
  yolort/utils/yolo.py
Labels: enhancement, API

#167 Support loading model weight from ultralytics
  .gitignore
  requirements.txt
  test/test_data_pipeline.py
  test/test_hooks_utils.py
  test/test_image_utils.py
  test/test_models.py
  test/test_models_anchor_utils.py
  test/test_models_common.py
  test/test_utils.py
  test/test_v5.py
  yolort/__init__.py
  yolort/models/__init__.py
  yolort/models/_utils.py
  yolort/models/common.py
  yolort/models/darknet.py
  yolort/models/experimental.py
  yolort/models/path_aggregation_network.py
  yolort/models/transformer.py
  yolort/models/yolo.py
  yolort/models/yolo_module.py
  yolort/utils/__init__.py
  yolort/utils/activations.py
  yolort/utils/flash_utils.py
  yolort/utils/hooks.py
  yolort/utils/image_utils.py
  yolort/utils/update_module_state.py
  yolort/v5/__init__.py
  yolort/v5/data/coco128.yaml
  yolort/v5/data/hyps/hyp.scratch.yaml
  yolort/v5/helper.py
  yolort/v5/models/__init__.py
  yolort/v5/models/common.py
  yolort/v5/models/experimental.py
  yolort/v5/models/yolo.py
  yolort/v5/models/yolov5s.yaml
  yolort/v5/utils/__init__.py
  yolort/v5/utils/augmentations.py
  yolort/v5/utils/autoanchor.py
  yolort/v5/utils/callbacks.py
  yolort/v5/utils/datasets.py
  yolort/v5/utils/downloads.py
  yolort/v5/utils/general.py
  yolort/v5/utils/loss.py
  yolort/v5/utils/metrics.py
  yolort/v5/utils/plots.py
  yolort/v5/utils/torch_utils.py
Labels: enhancement, API, bc-breaking

#169 Update statement for loading checkpoint from ultralytics
  README.md
  notebooks/README.md
  notebooks/how-to-align-with-ultralytics-yolov5.ipynb
Labels: documentation

#172 Fix dynamic shape when exporting ONNX
  notebooks/export-onnx-inference-onnxruntime.ipynb
Labels: bug / fix

#171 Add ONNXRuntime C++ inference code
  deployment/onnxruntime/CMakeLists.txt
  deployment/onnxruntime/README.md
  deployment/onnxruntime/cmdline.h
  deployment/onnxruntime/main.cpp
Labels: enhancement, deployment

#174 Add ONNXRuntime support statement
  README.md
  deployment/onnxruntime/README.md
Labels: documentation

#178 Add ONNXRuntime python inference.
  deployment/onnxruntime-python/README.md
  deployment/onnxruntime-python/example.py
Labels: enhancement, deployment

#175 Add CLI tool for exporting ONNX models
  tools/export_model.py
Labels: enhancement

#179 Refactor `load_from_yolov5` in `YOLOv5`
  .gitignore
  README.md
  test/test_models.py
  yolort/models/__init__.py
  yolort/models/yolo.py
  yolort/models/yolo_module.py
  yolort/utils/update_module_state.py
  yolort/v5/helper.py
Labels: enhancement, code quality
