Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-06, with the labels that each got.

#117 Add updating weights example from ultralytics/yolov5
  .gitignore
  notebooks/align_with_ultralytics_yolov5.ipynb
  yolort/utils/image_utils.py
Labels: enhancement

#121 Update alignment with ultralytics docs
  README.md
  notebooks/how-to-align-with-ultralytics-yolov5.ipynb
  yolort/models/yolo.py
  yolort/utils/update_module_state.py
Labels: API, documentation

#113 AnchorGenerator forces torch.arange in fp32 to allow export to onnx
  yolort/models/anchor_utils.py
Labels: enhancement

#124 Fixing normalization in dataloader
  yolort/models/transform.py
Labels: bug / fix

#126 Update jit graph visualization
  notebooks/visualize-jit-models.ipynb
Labels: bug / fix, documentation

#128 Fixing trainer with lightning
  test/common_utils.py
  test/test_data_pipeline.py
  test/test_onnx.py
  yolort/data/data_module.py
  yolort/models/yolo_module.py
  yolort/train.py
Labels: bug / fix
