Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-03, with the labels that each got.

#76 Add PyTorch 1.8 to CI
  .github/workflows/ci_test.yml
Labels: enhancement

#81 Remove LayerNorm in Transformer
  test/test_models.py
  yolort/models/__init__.py
  yolort/models/transformer.py
  yolort/models/yolo.py
Labels: enhancement

#79 Allow loading of user-trained ultralytics models
  test/test_utils.py
  yolort/models/path_aggregation_network.py
  yolort/models/yolo_module.py
  yolort/utils/update_module_state.py
Labels: enhancement

#82 Rename parameters to keep consistency
  test/test_models.py
  test/test_onnx.py
  test/test_utils.py
  yolort/models/__init__.py
  yolort/models/backbone_utils.py
  yolort/models/box_head.py
  yolort/models/common.py
  yolort/models/darknet.py
  yolort/models/path_aggregation_network.py
  yolort/models/transformer.py
  yolort/models/yolo.py
Labels: documentation

#84 Decoupling path dependence in notebooks
  .github/workflows/ci_test.yml
  notebooks/export-onnx-inference-onnxruntime.ipynb
  notebooks/export-relay-inference-tvm.ipynb
  notebooks/inference-pytorch-export-libtorch.ipynb
  test/test_image_utils.py
  yolort/utils/__init__.py
  yolort/utils/image_utils.py
Labels: documentation

#85 Add Docs with Sphinx
  docs/Makefile
  docs/make.bat
  docs/requirements.txt
  docs/source/_static/rt-logo.png
  docs/source/_static/yolort-logo.png
  docs/source/_templates/footer.html
  docs/source/_templates/searchbox.html
  docs/source/conf.py
  docs/source/datasets.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/models.rst
  docs/source/utils.rst
Labels: documentation, enhancement
