Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-05, with the labels that each got.

#103 Cleanup data pipeline
  test/test_data_pipeline.py
  test/test_engine.py
  yolort/data/__init__.py
  yolort/data/_helper.py
  yolort/data/data_module.py
  yolort/data/data_pipeline.py
  yolort/data/detection_pipeline.py
  yolort/models/yolo_module.py
Labels: API, enhancement

#104 Update README
  README.md
Labels: documentation

#109 Workaround on YOLOTransform to support fixed size input
  notebooks/export-onnx-inference-onnxruntime.ipynb
  notebooks/export-relay-inference-tvm.ipynb
  notebooks/inference-pytorch-export-libtorch.ipynb
  test/test_engine.py
  test/test_onnx.py
  yolort/models/transform.py
  yolort/models/yolo_module.py
Labels: enhancement

#110 Add missing copyright, cleanup and fix docs
  .github/ISSUE_TEMPLATE/bug-report.md
  docs/source/notebooks/export_onnx_inference_onnxruntime.ipynb
  docs/source/notebooks/export_relay_inference_tvm.ipynb
  docs/source/notebooks/inference_pytorch_export_libtorch.ipynb
  docs/source/notebooks/load_model_as_ultralytics.ipynb
  docs/source/notebooks/visualize_jit_models.ipynb
  yolort/utils/graph_utils.py
  yolort/utils/image_utils.py
  yolort/utils/yolo2coco.py
Labels: bug / fix, code quality

#111 AnchorGenerator will use dtype of input feature_maps
  yolort/models/anchor_utils.py
Labels: enhancement
