Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2021-07, with the labels that each got.

#116 Add anchor / target assignment visualization notebook
  docs/source/index.rst
  docs/source/notebooks/.gitignore
  docs/source/notebooks/anchor_label_assignment_visualization.ipynb
  docs/source/notebooks/how_to_align_with_ultralytics_yolov5.ipynb
  docs/source/notebooks/load_model_as_ultralytics.ipynb
  docs/source/notebooks/model_graph_visualization.ipynb
  docs/source/notebooks/visualize_jit_models.ipynb
  notebooks/anchor-label-assignment-visualization.ipynb
  notebooks/training-samples-visualization.ipynb
Labels: documentation, enhancement

#136 Update C++ interfaces of TorchVision to 0.9.0+
  deployment/README.md
  deployment/src/main.cpp
Labels: enhancement

#138 Attach libtorch inference results
  README.md
  deployment/libtorch/main.cpp
Labels: enhancement

#140 Added more descriptive error logging
  deployment/libtorch/main.cpp
Labels: documentation

#125 Refactorring skeleton of SetCriterion
  test/test_engine.py
  test/test_hooks_utils.py
  test/test_models.py
  test/test_models_anchor_utils.py
  test/test_models_utils.py
  yolort/models/_utils.py
  yolort/models/anchor_utils.py
  yolort/models/box_head.py
  yolort/models/yolo.py
  yolort/utils/__init__.py
  yolort/utils/hooks_utils.py
Labels: code quality, enhancement

#145 Add ncnn deployment examples
  deployment/ncnn/CMakeLists.txt
  deployment/ncnn/README.md
  deployment/ncnn/export_onnx.py
  deployment/ncnn/main.cpp
  deployment/ncnn/tools/__init__.py
  deployment/ncnn/tools/yolort_deploy_friendly.py
  deployment/ncnn/yolort-opt.param
  test/test_models_common.py
  yolort/models/common.py
Labels: deployment, enhancement
