Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-05, with the labels that each got.

#375 Add CLI tool for converting YOLO-format to MSCOCO
  tools/convert_txt_to_json.py
  yolort/utils/__init__.py
  yolort/utils/annotations_converter.py
  yolort/utils/yolo2coco.py
Labels: enhancement, API

#410 Add Song Lin as co-authors
  README.md
Labels: documentation

#409 Support TensorRT fp16 inference
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
  yolort/runtime/trt_helper.py
Labels: enhancement
