Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-03, with the labels that each got.

#342 Constructs YOLOv5 model with TorchVision MobileNetV3 backbone
  yolort/models/box_head.py
  yolort/models/yolo_lite.py
Labels: enhancement, API

#343 Use C3 following the model specification of YOLOv5
  test/test_models.py
  yolort/models/box_head.py
  yolort/models/yolo_lite.py
Labels: enhancement

#351 Move bias initializations from private methods to constructors
  yolort/models/anchor_utils.py
  yolort/models/box_head.py
  yolort/utils/image_utils.py
Labels: code quality

#352 Fix `anchor_grids` for custom trained checkpoints
  yolort/utils/update_module_state.py
Labels: bug / fix

#354 Update doc-strings and tutorials
  notebooks/comparison-between-yolort-vs-yolov5.ipynb
  notebooks/how-to-align-with-ultralytics-yolov5.ipynb
  yolort/utils/update_module_state.py
  yolort/utils/visualizer.py
Labels: documentation, code quality

#285 Fix `num_anchors` in load_from_ultralytics
  test/test_utils.py
  yolort/utils/update_module_state.py
Labels: bug / fix

#355 Remove lightning dependencies
  .github/workflows/ci-test.yml
  requirements.txt
  test/test_data_pipeline.py
  test/test_models_yolov5.py
  test/test_trainer.py
  tools/eval_metric.py
  yolort/data/__init__.py
  yolort/models/_utils.py
  yolort/models/darknet.py
  yolort/models/darknetv4.py
  yolort/models/darknetv6.py
  yolort/models/path_aggregation_network.py
  yolort/models/transformer.py
  yolort/trainer/lightning_task.py
Labels: dependencies

#358 Fix lightning import for building docs
  yolort/data/coco_eval.py
  yolort/data/data_module.py
Labels: dependencies

#359 Add PyTorch 1.11.0 in GH Actions
  .github/workflows/ci-test.yml
  README.md
  setup.py
  yolort/utils/__init__.py
  yolort/utils/dependency.py
  yolort/v5/helper.py
Labels: code quality, dependencies

#362 Remove openvino support temporarily
  yolort/runtime/openvino_helper.py
  yolort/runtime/y_openvino.py
Labels: code quality, dependencies

#363 Fix building docs and update docstrings
  deployment/libtorch/README.md
  docs/requirements.txt
  requirements.txt
Labels: documentation, code quality

#369 Fix ImportError of circular reference
  test/test_data_pipeline.py
  test/test_utils.py
  yolort/data/__init__.py
  yolort/data/_helper.py
  yolort/models/_utils.py
  yolort/models/yolo.py
  yolort/models/yolov5.py
  yolort/relay/trt_inference.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/y_tensorrt.py
  yolort/utils/__init__.py
  yolort/utils/update_module_state.py
Labels: bug / fix, code quality, dependencies, bc-breaking

#366 Improves optional imports
  yolort/data/data_module.py
  yolort/relay/trt_graphsurgeon.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/y_tensorrt.py
  yolort/utils/dependency.py
Labels: enhancement, code quality, dependencies

#367 Improves more optional module imports
  yolort/data/coco.py
  yolort/data/coco_eval.py
  yolort/relay/ir_visualizer.py
  yolort/relay/trt_graphsurgeon.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/y_tensorrt.py
  yolort/utils/image_utils.py
  yolort/utils/visualizer.py
  yolort/v5/models/yolo.py
  yolort/v5/utils/augmentations.py
  yolort/v5/utils/general.py
  yolort/v5/utils/plots.py
  yolort/v5/utils/torch_utils.py
Labels: enhancement, code quality, dependencies

#372 Update pre-commit and actions/cache
  .github/workflows/ci-test.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pypi-release.yml
  .pre-commit-config.yaml
Labels: dependencies

#373 Move `load_from_ultralytics` into _checkpoint.py
  test/test_utils.py
  yolort/models/_checkpoint.py
  yolort/models/_utils.py
  yolort/models/yolo.py
  yolort/relay/trt_graphsurgeon.py
  yolort/relay/trt_inference.py
  yolort/utils/update_module_state.py
Labels: API, code quality, bc-breaking
