Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-01, with the labels that each got.

#264 Fix list expanding in export_model.py
  tools/export_model.py
Labels: bug / fix

#267 Fix TorchScript exporting for custom checkpoints
  test/test_models.py
  yolort/models/_utils.py
  yolort/models/anchor_utils.py
  yolort/models/box_head.py
  yolort/models/yolo.py
  yolort/runtime/trt_helper.py
Labels: bug / fix

#269 Fix arguments in export_model.py
  tools/export_model.py
Labels: bug / fix

#275 Add unittests for YOLOGraphSurgeon
  test/test_runtime.py
Labels: code quality

#283 Fix TensorRT Python examples
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
  yolort/runtime/trt_helper.py
  yolort/runtime/yolo_graphsurgeon.py
Labels: bug / fix, documentation

#284 Fix alignment notebook with yolov5
  notebooks/how-to-align-with-ultralytics-yolov5.ipynb
Labels: bug / fix, documentation

#286 Set opencv as optional
  yolort/utils/image_utils.py
  yolort/v5/utils/augmentations.py
  yolort/v5/utils/general.py
  yolort/v5/utils/plots.py
Labels: dependencies

#287 Update PyTorch to 1.10 in TVM Relay VM notebook
  notebooks/export-relay-inference-tvm.ipynb
Labels: documentation

#288 Use `EfficientNMS_TRT` plugin when exporting TensorRT
  deployment/tensorrt/main.cpp
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
  yolort/runtime/logits_decoder.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_tensorrt.py
  yolort/runtime/yolo_graphsurgeon.py
Labels: enhancement, code quality

#290 Add ablation experiment results with `EfficientNMS_TRT`
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
Labels: documentation

#292 Deploy docs with Material Sphinx Theme
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  notebooks/export-onnx-inference-onnxruntime.ipynb
Labels: documentation

#294 Install yolort in GH Actions
  .github/workflows/ci-test.yml
Labels: code quality, dependencies
