Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-04, with the labels that each got.

#386 Update dependencies
  .github/workflows/ci-test.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pypi-release.yml
  .pre-commit-config.yaml
  README.md
  setup.py
  test/test_trainer.py
Labels: dependencies

#388 Update badges and fix docs
  .github/workflows/ci-test.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pypi-release.yml
  README.md
Labels: documentation, dependencies

#389 Fix Windows compatibility for TensorRT C++ example
  deployment/tensorrt/CMakeLists.txt
  deployment/tensorrt/README.md
Labels: bug / fix, enhancement

#391 Add more badges
  README.md
  deployment/libtorch/README.md
  deployment/ncnn/README.md
  deployment/onnxruntime/README.md
  deployment/tensorrt/README.md
Labels: documentation

#396 Fix TensorRT Windows Python interface compatibility
  yolort/runtime/y_tensorrt.py
Labels: bug / fix
