Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-06, with the labels that each got.

#413 Support exporting vanilla ONNX `nms` and `batched_nms`
  yolort/relay/__init__.py
  yolort/relay/head_helper.py
  yolort/runtime/ort_helper.py
Labels: enhancement

#414 Refactor `FakeYOLO` and `VanillaONNXBuilder`
  tools/export_model.py
  yolort/relay/__init__.py
  yolort/relay/head_helper.py
  yolort/runtime/ort_helper.py
Labels: enhancement

#365 Introduce `YOLOTransform` using OpenCV
  yolort/runtime/transform.py
Labels: enhancement

#415 Cleanup Module `Detect`
  yolort/relay/head_helper.py
  yolort/v5/models/common.py
  yolort/v5/models/yolo.py
Labels: code quality

#417 Cleanup boxes decoding on `FakePostProcess`
  yolort/models/box_head.py
  yolort/relay/head_helper.py
  yolort/runtime/ort_helper.py
Labels: code quality

#419 Add `export_type` for exporting OpenVINO
  yolort/relay/head_helper.py
Labels: enhancement, deployment

#425 Bump pre-commits and actions dependencies
  .github/workflows/ci-test.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pypi-release.yml
  .pre-commit-config.yaml
  README.md
  hubconf.py
  test/__init__.py
  test/test_models.py
  test/test_models_transform.py
  test/test_utils.py
  test/test_v5.py
  tools/eval_metric.py
  yolort/__init__.py
  yolort/data/coco_eval.py
  yolort/data/data_module.py
  yolort/data/transforms.py
  yolort/models/_utils.py
  yolort/models/anchor_utils.py
  yolort/models/darknet.py
  yolort/models/darknetv4.py
  yolort/models/darknetv6.py
  yolort/models/path_aggregation_network.py
  yolort/models/transform.py
  yolort/models/transformer.py
  yolort/models/yolo.py
  yolort/models/yolo_lite.py
  yolort/models/yolov5.py
  yolort/relay/trace_wrapper.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/y_tensorrt.py
  yolort/utils/__init__.py
  yolort/utils/hooks.py
  yolort/v5/models/__init__.py
  yolort/v5/models/common.py
  yolort/v5/models/yolo.py
  yolort/v5/utils/__init__.py
  yolort/v5/utils/augmentations.py
  yolort/v5/utils/autoanchor.py
  yolort/v5/utils/metrics.py
  yolort/v5/utils/plots.py
Labels: dependencies

#426 Add Weights and Biases to `MetricLogger` Class
  tools/eval_metric.py
  yolort/utils/logger.py
Labels: enhancement

#431 Compatibility fixes for numpy 1.23
  yolort/utils/visualizer.py
Labels: bug / fix

#427 Compatibility fixes for Windows systems
  yolort/data/coco.py
  yolort/data/coco_eval.py
  yolort/data/data_module.py
  yolort/relay/ir_visualizer.py
  yolort/relay/trt_graphsurgeon.py
  yolort/runtime/trt_helper.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/y_tensorrt.py
  yolort/utils/__init__.py
  yolort/utils/image_utils.py
  yolort/utils/logger.py
  yolort/utils/visualizer.py
  yolort/v5/models/yolo.py
  yolort/v5/utils/augmentations.py
  yolort/v5/utils/general.py
  yolort/v5/utils/plots.py
  yolort/v5/utils/torch_utils.py
Labels: bug / fix

#432 Initial support for YOLOv6 TensorRT Inference
  README.md
  deployment/tensorrt-yolov6/CMakeLists.txt
  deployment/tensorrt-yolov6/README.md
  deployment/tensorrt-yolov6/build_model/CMakeLists.txt
  deployment/tensorrt-yolov6/build_model/main.cpp
  deployment/tensorrt-yolov6/main.cpp
  deployment/tensorrt-yolov6/trt_dep.cpp
  deployment/tensorrt-yolov6/trt_dep.hpp
Labels: enhancement, deployment
