Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-12, with the labels that each got.

#473 Remove lightning dependency in unit tests
  .github/workflows/ci-test.yml
  .github/workflows/code-format.yml
  .github/workflows/gh-pages.yml
  .github/workflows/pypi-release.yml
  .pre-commit-config.yaml
  test/test_data_pipeline.py
  test/test_models_yolov5.py
  test/test_trainer.py
  test/test_utils.py
Labels: bug / fix, code quality, dependencies

#470 Make compatible with yolov5 6.2 release
  yolort/v5/models/yolo.py
Labels: bug / fix

#474 Rename to `DetectionModel`
  yolort/v5/models/yolo.py
Labels: code quality

#462 Set RGB mode in read_image
  yolort/models/yolov5.py
  yolort/runtime/y_tensorrt.py
Labels: bug / fix
