Repository zhiqwang/yolov5-rt-stack, pull requests merged in 2022-02, with the labels that each got.

#298 Replaced to_tensor() with pil_to_tensor() + convert_image_dtype()
  yolort/data/coco_eval.py
  yolort/data/transforms.py
Labels: code quality

#293 Fix the consistency of pre-processing with yolov5
  .github/workflows/ci-test.yml
  notebooks/inference-pytorch-export-libtorch.ipynb
  test/test_engine.py
  test/test_models.py
  test/test_models_transform.py
  test/test_onnx.py
  yolort/models/__init__.py
  yolort/models/transform.py
  yolort/models/yolo_module.py
  yolort/v5/utils/augmentations.py
Labels: bug / fix, bc-breaking

#299 Update Contributing and badges
  README.md
Labels: documentation

#300 Add comparison docs for yolov5 & yolort
  docs/source/conf.py
  docs/source/index.rst
  docs/source/notebooks/comparison-between-yolort-vs-yolov5.ipynb
  notebooks/comparison-between-yolort-vs-yolov5.ipynb
  test/test_utils.py
  yolort/models/transform.py
  yolort/models/yolo_module.py
Labels: documentation

#301 Support fixed shape inference in pre-processing
  notebooks/comparison-between-yolort-vs-yolov5.ipynb
  test/test_models_transform.py
  test/test_onnx.py
  yolort/models/transform.py
  yolort/models/yolo_module.py
Labels: enhancement, API

#302 Fix pre-processing for TVM VM inference
  notebooks/comparison-between-yolort-vs-yolov5.ipynb
  notebooks/export-relay-inference-tvm.ipynb
  test/test_models_transform.py
  test/test_onnx.py
  yolort/models/box_head.py
  yolort/models/transform.py
  yolort/models/yolo_module.py
  yolort/runtime/logits_decoder.py
Labels: bug / fix, API

#303 Compatible with Windows for LibTorch deployment
  deployment/libtorch/README.md
  deployment/libtorch/main.cpp
Labels: bug / fix

#304 Update Docs and Readme
  README.md
  docs/source/index.rst
  notebooks/comparison-between-yolort-vs-yolov5.ipynb
Labels: documentation

#305 Add letterbox for TRT inference
  deployment/tensorrt/main.cpp
Labels: enhancement, deployment

#307 Refactoring TensorRT Python interface
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
  yolort/runtime/trt_helper.py
  yolort/runtime/y_tensorrt.py
  yolort/runtime/yolo_graphsurgeon.py
Labels: API, code quality

#308 Add docstrings for input type in `YOLOTransform`
  yolort/models/transform.py
Labels: documentation, code quality

#311 Add TensorRT installation instructions to tutorial
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
Labels: documentation

#312 Refactor TensorRT engine export
  notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb
  test/test_relaying.py
  test/test_runtime.py
  yolort/relaying/__init__.py
  yolort/relaying/logits_decoder.py
  yolort/relaying/trt_graphsurgeon.py
  yolort/relaying/yolo_inference.py
  yolort/runtime/__init__.py
  yolort/runtime/trt_helper.py
Labels: documentation, API, deployment

#313 Rename relaying to relay
  notebooks/export-relay-inference-tvm.ipynb
  notebooks/model-graph-visualization.ipynb
  test/test_relay.py
  test/tracing/trace_model.py
  yolort/relay/__init__.py
  yolort/relay/ir_visualizer.py
  yolort/relay/logits_decoder.py
  yolort/relay/trace_wrapper.py
  yolort/relay/trt_graphsurgeon.py
  yolort/relay/trt_inference.py
  yolort/runtime/trt_helper.py
Labels: API, bc-breaking

#314 Move Lightning wrapper into trainer
  test/test_models_yolov5.py
  test/test_trainer.py
  yolort/models/__init__.py
  yolort/models/_utils.py
  yolort/models/yolov5.py
  yolort/trainer/__init__.py
  yolort/trainer/lightning_task.py
Labels: API, bc-breaking

#315 Fix docs and add docstrings for `YOLOv5`
  docs/source/models.rst
  yolort/models/yolov5.py
Labels: documentation

#319 Refactor ONNX export and tutorial
  deployment/onnxruntime/README.md
  notebooks/export-onnx-inference-onnxruntime.ipynb
  test/test_runtime.py
  test/test_runtime_ort.py
  tools/export_model.py
  yolort/models/yolov5.py
  yolort/runtime/ort_helper.py
Labels: documentation, API

#320 Support multiple batches for exporting ONNX with pre-processing
  test/test_runtime_ort.py
  tools/export_model.py
  yolort/runtime/ort_helper.py
Labels: enhancement, deployment

#321 Fix pre-processing in TensorRT C++ example
  deployment/tensorrt/main.cpp
Labels: bug / fix

#323 Support loading with TensorRT SerializedModel
  deployment/tensorrt/CMakeLists.txt
  deployment/tensorrt/main.cpp
Labels: enhancement, deployment

#326 Support exporting TensorRT serialized engine in CLI tools
  deployment/tensorrt/README.md
  deployment/tensorrt/main.cpp
  tools/export_model.py
  yolort/runtime/trt_helper.py
Labels: documentation, enhancement

#327 Enhance `PredictorORT` to adapt to more scenarios
  README.md
  deployment/onnxruntime/README.md
  notebooks/export-onnx-inference-onnxruntime.ipynb
  test/test_runtime_ort.py
  yolort/data/__init__.py
  yolort/data/_helper.py
  yolort/runtime/y_onnxruntime.py
  yolort/runtime/y_tensorrt.py
Labels: enhancement, bc-breaking

#329 Specify version when release Python wheel
  .github/workflows/pypi-release.yml
  setup.cfg
  setup.py
Labels: bug / fix

#331 Bump version to 0.7.0
  setup.py
Labels: dependencies

#335 Add missing version param in export_tensorrt
  tools/export_model.py
Labels: bug / fix

#334 Init OpenVINO conversion utilities
  yolort/runtime/openvino_helper.py
Labels: enhancement, deployment

#336 Init OpenVINO inference instance
  yolort/runtime/openvino_helper.py
  yolort/runtime/y_openvino.py
Labels: enhancement, deployment
